# Settings (predefined)
speeds <- list(slow1 = list(iterations = 100000,
                            adapt_delta = 0.999,
                            tree_depth = 15,
                            chains = 4),
               slow2 = list(iterations =  200000, 
                            adapt_delta = 0.999,
                            tree_depth = 15,
                            chains = 4),
               slow3 = list(iterations =  300000, 
                            adapt_delta = 0.999,
                            tree_depth = 15,
                            chains = 4),
               fast = list(iterations =  12000, 
                           adapt_delta = 0.9,
                           tree_depth = 12,
                           chains = 4))

model_params_combinations <- function(chosen_speed) {
    list(
        list(dataset = "GL", 
                ll = "Y",       
                chains = speeds[[chosen_speed]]$chains,     
                iter = speeds[[chosen_speed]]$iterations,  
                ad = speeds[[chosen_speed]]$adapt_delta,      
                td = speeds[[chosen_speed]]$tree_depth),
        list(dataset = "BG", 
                ll = "Y",       
                chains = speeds[[chosen_speed]]$chains,     
                iter = speeds[[chosen_speed]]$iterations,  
                ad = speeds[[chosen_speed]]$adapt_delta,      
                td = speeds[[chosen_speed]]$tree_depth),
        list(dataset = "BG", 
                ll = "N",       
                chains = speeds[[chosen_speed]]$chains,     
                iter = speeds[[chosen_speed]]$iterations,  
                ad = speeds[[chosen_speed]]$adapt_delta,      
                td = speeds[[chosen_speed]]$tree_depth),
        list(dataset = "LT", 
                ll = "Y",       
                chains = speeds[[chosen_speed]]$chains,     
                iter = speeds[[chosen_speed]]$iterations,  
                ad = speeds[[chosen_speed]]$adapt_delta,      
                td = speeds[[chosen_speed]]$tree_depth),
        list(dataset = "LT", 
                ll = "N",       
                chains = speeds[[chosen_speed]]$chains,     
                iter = speeds[[chosen_speed]]$iterations,  
                ad = speeds[[chosen_speed]]$adapt_delta,      
                td = speeds[[chosen_speed]]$tree_depth),
        list(dataset = "BM", 
                ll = "Y",       
                chains = speeds[[chosen_speed]]$chains,     
                iter = speeds[[chosen_speed]]$iterations,  
                ad = speeds[[chosen_speed]]$adapt_delta,      
                td = speeds[[chosen_speed]]$tree_depth)
    )
} 



