# Libraries
suppressMessages(library(data.table))
suppressMessages(library(dplyr))
suppressMessages(library(ggmap))
suppressMessages(library(ggplot2))
suppressMessages(library(sf))
suppressMessages(library(tidyr))
suppressMessages(library(ggplot2))
suppressMessages(library(grid))
suppressMessages(library(gridExtra))
suppressMessages(library(maptools))
suppressMessages(library(plyr))
suppressMessages(library(reshape))
suppressMessages(library(xlsx))
