name: msc
channels:
  - conda-forge
dependencies:
  - ipykernel
  - jupyter
  - matplotlib
  - networkx=2.4.*
  - numpy
  - pandas
  - python-louvain=0.13
  - scikit-learn
  - seaborn
  - statsmodels